# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      #sudo apt-get update
      #sudo apt-get upgrade -y
      #sudo apt-add-repository ppa:ansible/ansible
      #sudo apt-get update
      #sudo apt-get install ansible -y
      ansible --version
      echo "stack ID is $stackId"
      
      
      # Use the environment variables input below to pass secret variables to this script
#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml'
#    mavenOptions: '-Xmx3072m'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.8'
#    jdkArchitectureOption: 'x64'
#    publishJUnitResults: false
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    goals: 'package'