parameters:
  name: ''  # defaults for any parameters that aren't specified
  pool: {}

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - script: echo "hello " . ${{ parameters.rfcId }}
